engines:
  eslint:
    enabled: true
    channel: "eslint-3"
    checks:
      import/no-unresolved:
        enabled: false
  fixme:
    enabled: true
ratings:
  paths:
    - "**.ts"
    - "src/*"
    - "src/**/*"
    - "spec/*"
    - "spec/**/*"
    - "ci/*"
