instrumentation:
    root: .
    default-excludes: true
    excludes: [
        "spec/**",
    ]
reporting:
    print: summary
    reports:
        - lcov
    dir: ./coverage
check:
    global:
        statements: 100
        lines: 100
        branches: 100
        functions: 100
