version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: ./scripts/ci.sh
      - type: deploy
        name: "Publish to npm"
        command: |
          if [ "${CIRCLE_BRANCH}" == "master" ]; then
            echo "Publishing latest release"
            echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> ~/.npmrc
            yarn semantic-release || true
          else
            echo "Skipping publication in non-release branch"
          fi
